export const AUTH_MESSAGE = {
  EMAIL_INVALID: 'Email không hợp lệ',
  EMAIL_REQUIRED: 'Vui lòng nhập email',
  EMAIL_EXISTS: 'Email đã tồn tại',
  EMAIL_NOT_EMPTY: 'Email không được để trống',
  PASSWORD_INVALID_MIN_LENGTH: 'Mật khẩu phải có ít nhất 6 ký tự',
  PASSWORD_INVALID_LENGTH: 'Mật khẩu phải có ít nhất 6 - 180 ký tự',
  PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu',
  LOGIN_FAILED: 'Đăng nhập thất bại, vui lòng kiểm tra lại thông tin',
  FULLNAME_NOT_EMPTY: 'Tên không được để trống',
  FULLNAME_INVALID_MIN_LENGTH: 'Họ và tên phải có ít nhất 10 ký tự',
  FULLNAME_INVALID_LENGTH: 'Họ và tên phải có ít nhất 10 - 180 ký tự',
  VALIDATION_ERROR: 'Dữ liệu không hợp lệ',
  CONFIRM_PASSWORD_INVALID_LENGTH: 'Mật khẩu phải có ít nhất 6 - 180 ký tự',
  CONFIRM_PASSWORD_INVALID: 'Mật khẩu nhập lại không khớp',
  EMAIL_NOT_EXISTS: 'Email không tồn tại',
  EMAIL_OR_PASSWORD_NOT_EXISTS: 'Email hoặc mật khẩu không chính xác',
  REGISTER_SUCCESS: 'Đăng ký thành công, vui lòng kiểm tra email để kích hoạt tài khoản',
  LOGIN_SUCCESS: 'Đăng nhập thành công',
  REFRESH_TOKEN_NOT_EMPTY: 'Refresh token không được để trống',
  REFRESH_TOKEN_NOT_EXISTS: 'Refresh token không tồn tại',
  REFRESH_TOKEN_INVALID: 'Refresh token không hợp lệ',
  ACCESS_TOKEN_NOT_EMPTY: 'Access token không được để trống',
  ACCESS_TOKEN_NOT_EXISTS: 'Access token không tồn tại',
  ACCESS_TOKEN_INVALID: 'Access token không hợp lệ',
  LOGOUT_SUCCESS: 'Đăng xuất thành công',
  PASSWORD_NOT_EMPTY: 'Mật khẩu không được để trống',
  PASSWORD_NOT_EXISTS: 'Mật khẩu không tồn tại',
  CHANGE_PASSWORD_SUCCESS: 'Đổi mật khẩu thành công',
  USER_NOT_VERIFIED: 'Tài khoản chưa được xác thực',
  FORGOT_PASSWORD_SUCCESS: 'Vui lòng kiểm tra email để đổi mật khẩu',
  FORGOT_PASSWORD_TOKEN_NOT_EMPTY: 'Forgot token không được để trống',
  FORGOT_PASSWORD_TOKEN_NOT_EXISTS: 'Forgot token không tồn tại',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Xác thực Forgot token hợp lệ',
  FORGOT_PASSWORD_TOKEN_NOT_FOUND: 'Không tìm thấy Forgot token',
  RESET_PASSWORD_SUCCESS: 'Đổi mật khâu thành công'
}

export const USER_MESSAGE = {
  USER_NOT_EXISTS: 'Tài khoản không tồn tại',
  USER_NOT_FOUND: 'Không tìm thấy tài khoản'
}
